/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalInterface;
import java.util.ArrayList;
import pecl.*;

/**
 *
 * @author Oqueo
 */
public class MainWindow extends javax.swing.JFrame {
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        Hospital hospital = null;
        hospital = new Hospital(new Reception(hospital), new VaccRoom(hospital), new ObservationRoom(hospital),this);
        AuxWorker a1 = new AuxWorker(1,10,hospital);
        hospital.getReception().setAuxWorker(a1);
        a1.start();
        AuxWorker a2 = new AuxWorker(2,20,hospital);
        hospital.getVaccRoom().setAuxWorker(a2);
        a2.start();
        for (int i = 1; i<= 10; i++)
        {
            HcareWorker worker = new HcareWorker(i, 0,hospital);
            worker.start();
        }
        for(int i = 1; i <= 2000; i++)
        {
            Patient patient = new Patient(i, hospital);
            patient.start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReceptionLabel = new javax.swing.JLabel();
        ReceptionTextPane = new javax.swing.JScrollPane();
        ReceptionText = new javax.swing.JTextArea();
        RPatientLabel = new javax.swing.JLabel();
        RPatientTextPane = new javax.swing.JScrollPane();
        RPatientText = new javax.swing.JTextArea();
        RAuxiliaryLabel = new javax.swing.JLabel();
        RAuxiliaryTextPane = new javax.swing.JScrollPane();
        RAuxiliaryText = new javax.swing.JTextArea();
        RestroomLabel = new javax.swing.JLabel();
        RestroomTextPane = new javax.swing.JScrollPane();
        RestroomText = new javax.swing.JTextArea();
        VaccinationRoomLabel = new javax.swing.JLabel();
        VDeskLabel1 = new javax.swing.JLabel();
        VDeskPane1 = new javax.swing.JScrollPane();
        VDesk1 = new javax.swing.JTextArea();
        VDeskLabel2 = new javax.swing.JLabel();
        VDeskPane2 = new javax.swing.JScrollPane();
        VDesk2 = new javax.swing.JTextArea();
        VDeskLabel3 = new javax.swing.JLabel();
        VDeskPane3 = new javax.swing.JScrollPane();
        VDesk3 = new javax.swing.JTextArea();
        VDeskLabel4 = new javax.swing.JLabel();
        VDeskPane4 = new javax.swing.JScrollPane();
        VDesk4 = new javax.swing.JTextArea();
        VDeskLabel5 = new javax.swing.JLabel();
        VDeskPane5 = new javax.swing.JScrollPane();
        VDesk5 = new javax.swing.JTextArea();
        VDeskLabel6 = new javax.swing.JLabel();
        VDeskPane6 = new javax.swing.JScrollPane();
        VDesk6 = new javax.swing.JTextArea();
        VDeskLabel7 = new javax.swing.JLabel();
        VDeskPane7 = new javax.swing.JScrollPane();
        VDesk7 = new javax.swing.JTextArea();
        VDeskLabel8 = new javax.swing.JLabel();
        VDeskPane8 = new javax.swing.JScrollPane();
        VDesk8 = new javax.swing.JTextArea();
        VDeskLabel9 = new javax.swing.JLabel();
        VDeskPane9 = new javax.swing.JScrollPane();
        VDesk9 = new javax.swing.JTextArea();
        VDeskLabel10 = new javax.swing.JLabel();
        VDeskPane10 = new javax.swing.JScrollPane();
        VDesk10 = new javax.swing.JTextArea();
        VVaccinesLabel = new javax.swing.JLabel();
        VVaccinesPane = new javax.swing.JScrollPane();
        VVaccinesText = new javax.swing.JTextArea();
        VAuxiliaryLabel = new javax.swing.JLabel();
        VAuxiliaryPane = new javax.swing.JScrollPane();
        VAuxiliaryText = new javax.swing.JTextArea();
        ObservationRoomLabel = new javax.swing.JLabel();
        ODeskLabel1 = new javax.swing.JLabel();
        ODeskPane1 = new javax.swing.JScrollPane();
        ODesk1 = new javax.swing.JTextArea();
        ODeskLabel2 = new javax.swing.JLabel();
        ODeskPane2 = new javax.swing.JScrollPane();
        ODesk2 = new javax.swing.JTextArea();
        ODeskLabel3 = new javax.swing.JLabel();
        ODeskPane3 = new javax.swing.JScrollPane();
        ODesk3 = new javax.swing.JTextArea();
        ODeskLabel4 = new javax.swing.JLabel();
        ODeskPane4 = new javax.swing.JScrollPane();
        ODesk4 = new javax.swing.JTextArea();
        ODeskLabel5 = new javax.swing.JLabel();
        ODeskPane5 = new javax.swing.JScrollPane();
        ODesk5 = new javax.swing.JTextArea();
        ODeskLabel6 = new javax.swing.JLabel();
        ODeskPane6 = new javax.swing.JScrollPane();
        ODesk6 = new javax.swing.JTextArea();
        ODeskLabel7 = new javax.swing.JLabel();
        ODeskPane7 = new javax.swing.JScrollPane();
        ODesk7 = new javax.swing.JTextArea();
        ODeskLabel8 = new javax.swing.JLabel();
        ODeskPane8 = new javax.swing.JScrollPane();
        ODesk8 = new javax.swing.JTextArea();
        ODeskLabel9 = new javax.swing.JLabel();
        ODeskPane9 = new javax.swing.JScrollPane();
        ODesk9 = new javax.swing.JTextArea();
        ODeskLabel10 = new javax.swing.JLabel();
        ODeskPane10 = new javax.swing.JScrollPane();
        ODesk10 = new javax.swing.JTextArea();
        ODeskLabel11 = new javax.swing.JLabel();
        ODeskPane11 = new javax.swing.JScrollPane();
        ODesk11 = new javax.swing.JTextArea();
        ODeskLabel12 = new javax.swing.JLabel();
        ODeskPane12 = new javax.swing.JScrollPane();
        ODesk12 = new javax.swing.JTextArea();
        ODeskLabel13 = new javax.swing.JLabel();
        ODeskPane13 = new javax.swing.JScrollPane();
        ODesk13 = new javax.swing.JTextArea();
        ODeskLabel14 = new javax.swing.JLabel();
        ODeskPane14 = new javax.swing.JScrollPane();
        ODesk14 = new javax.swing.JTextArea();
        ODeskLabel15 = new javax.swing.JLabel();
        ODeskPane15 = new javax.swing.JScrollPane();
        ODesk15 = new javax.swing.JTextArea();
        ODeskLabel16 = new javax.swing.JLabel();
        ODeskPane16 = new javax.swing.JScrollPane();
        ODesk16 = new javax.swing.JTextArea();
        ODeskLabel17 = new javax.swing.JLabel();
        ODeskPane17 = new javax.swing.JScrollPane();
        ODesk17 = new javax.swing.JTextArea();
        ODeskLabel18 = new javax.swing.JLabel();
        ODeskPane18 = new javax.swing.JScrollPane();
        ODesk18 = new javax.swing.JTextArea();
        ODeskLabel19 = new javax.swing.JLabel();
        ODeskPane19 = new javax.swing.JScrollPane();
        ODesk19 = new javax.swing.JTextArea();
        ODeskLabel20 = new javax.swing.JLabel();
        ODeskPane20 = new javax.swing.JScrollPane();
        ODesk20 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        ReceptionLabel.setText("RECEPTION");

        ReceptionTextPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ReceptionTextPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        ReceptionText.setEditable(false);
        ReceptionText.setColumns(20);
        ReceptionText.setRows(5);
        ReceptionTextPane.setViewportView(ReceptionText);

        RPatientLabel.setText("Patient");

        RPatientTextPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        RPatientTextPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        RPatientText.setEditable(false);
        RPatientText.setColumns(20);
        RPatientText.setRows(5);
        RPatientTextPane.setViewportView(RPatientText);

        RAuxiliaryLabel.setText("Auxiliary");

        RAuxiliaryTextPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        RAuxiliaryTextPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        RAuxiliaryText.setEditable(false);
        RAuxiliaryText.setColumns(20);
        RAuxiliaryText.setRows(5);
        RAuxiliaryTextPane.setViewportView(RAuxiliaryText);

        RestroomLabel.setText("RESTROOM");

        RestroomTextPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        RestroomTextPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        RestroomText.setEditable(false);
        RestroomText.setColumns(20);
        RestroomText.setRows(5);
        RestroomText.setPreferredSize(new java.awt.Dimension(400, 300));
        RestroomTextPane.setViewportView(RestroomText);

        VaccinationRoomLabel.setText("VACCINATION ROOM");

        VDeskLabel1.setText("Desk 1");

        VDeskPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        VDeskPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        VDeskPane1.setPreferredSize(new java.awt.Dimension(100, 50));

        VDesk1.setEditable(false);
        VDesk1.setColumns(20);
        VDesk1.setRows(5);
        VDeskPane1.setViewportView(VDesk1);

        VDeskLabel2.setText("Desk 2");

        VDeskPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        VDeskPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        VDeskPane2.setPreferredSize(new java.awt.Dimension(100, 50));

        VDesk2.setEditable(false);
        VDesk2.setColumns(20);
        VDesk2.setRows(5);
        VDeskPane2.setViewportView(VDesk2);

        VDeskLabel3.setText("Desk 3");

        VDeskPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        VDeskPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        VDeskPane3.setPreferredSize(new java.awt.Dimension(100, 50));

        VDesk3.setEditable(false);
        VDesk3.setColumns(20);
        VDesk3.setRows(5);
        VDeskPane3.setViewportView(VDesk3);

        VDeskLabel4.setText("Desk 4");

        VDeskPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        VDeskPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        VDeskPane4.setPreferredSize(new java.awt.Dimension(100, 50));

        VDesk4.setEditable(false);
        VDesk4.setColumns(20);
        VDesk4.setRows(5);
        VDeskPane4.setViewportView(VDesk4);

        VDeskLabel5.setText("Desk 5");

        VDeskPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        VDeskPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        VDeskPane5.setPreferredSize(new java.awt.Dimension(100, 50));

        VDesk5.setEditable(false);
        VDesk5.setColumns(20);
        VDesk5.setRows(5);
        VDeskPane5.setViewportView(VDesk5);

        VDeskLabel6.setText("Desk 6");

        VDeskPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        VDeskPane6.setToolTipText("");
        VDeskPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        VDeskPane6.setPreferredSize(new java.awt.Dimension(100, 50));

        VDesk6.setEditable(false);
        VDesk6.setColumns(20);
        VDesk6.setRows(5);
        VDeskPane6.setViewportView(VDesk6);

        VDeskLabel7.setText("Desk 7");

        VDeskPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        VDeskPane7.setToolTipText("");
        VDeskPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        VDeskPane7.setPreferredSize(new java.awt.Dimension(100, 50));

        VDesk7.setEditable(false);
        VDesk7.setColumns(20);
        VDesk7.setRows(5);
        VDeskPane7.setViewportView(VDesk7);

        VDeskLabel8.setText("Desk 8");

        VDeskPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        VDeskPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        VDeskPane8.setPreferredSize(new java.awt.Dimension(100, 50));

        VDesk8.setEditable(false);
        VDesk8.setColumns(20);
        VDesk8.setRows(5);
        VDeskPane8.setViewportView(VDesk8);

        VDeskLabel9.setText("Desk 9");

        VDeskPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        VDeskPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        VDeskPane9.setPreferredSize(new java.awt.Dimension(100, 50));

        VDesk9.setEditable(false);
        VDesk9.setColumns(20);
        VDesk9.setRows(5);
        VDeskPane9.setViewportView(VDesk9);

        VDeskLabel10.setText("Desk 10");

        VDeskPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        VDeskPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        VDeskPane10.setPreferredSize(new java.awt.Dimension(100, 50));

        VDesk10.setEditable(false);
        VDesk10.setColumns(20);
        VDesk10.setRows(5);
        VDeskPane10.setViewportView(VDesk10);

        VVaccinesLabel.setText("Available Vaccines");

        VVaccinesPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        VVaccinesPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        VVaccinesPane.setPreferredSize(new java.awt.Dimension(70, 30));

        VVaccinesText.setEditable(false);
        VVaccinesText.setColumns(20);
        VVaccinesText.setRows(5);
        VVaccinesPane.setViewportView(VVaccinesText);

        VAuxiliaryLabel.setText("Auxiliary");

        VAuxiliaryPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        VAuxiliaryPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        VAuxiliaryText.setEditable(false);
        VAuxiliaryText.setColumns(20);
        VAuxiliaryText.setRows(5);
        VAuxiliaryPane.setViewportView(VAuxiliaryText);

        ObservationRoomLabel.setText("OBSERVATION ROOM");

        ODeskLabel1.setText("Desk 1");

        ODeskPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane1.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk1.setEditable(false);
        ODesk1.setColumns(20);
        ODesk1.setRows(5);
        ODeskPane1.setViewportView(ODesk1);

        ODeskLabel2.setText("Desk 2");

        ODeskPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane2.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk2.setEditable(false);
        ODesk2.setColumns(20);
        ODesk2.setRows(5);
        ODeskPane2.setViewportView(ODesk2);

        ODeskLabel3.setText("Desk 3");

        ODeskPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane3.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk3.setEditable(false);
        ODesk3.setColumns(20);
        ODesk3.setRows(5);
        ODeskPane3.setViewportView(ODesk3);

        ODeskLabel4.setText("Desk 4");

        ODeskPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane4.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk4.setEditable(false);
        ODesk4.setColumns(20);
        ODesk4.setRows(5);
        ODeskPane4.setViewportView(ODesk4);

        ODeskLabel5.setText("Desk 5");

        ODeskPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane5.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk5.setEditable(false);
        ODesk5.setColumns(20);
        ODesk5.setRows(5);
        ODeskPane5.setViewportView(ODesk5);

        ODeskLabel6.setText("Desk 6");

        ODeskPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane6.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk6.setEditable(false);
        ODesk6.setColumns(20);
        ODesk6.setRows(5);
        ODeskPane6.setViewportView(ODesk6);

        ODeskLabel7.setText("Desk 7");

        ODeskPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane7.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk7.setEditable(false);
        ODesk7.setColumns(20);
        ODesk7.setRows(5);
        ODeskPane7.setViewportView(ODesk7);

        ODeskLabel8.setText("Desk 8");

        ODeskPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane8.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk8.setEditable(false);
        ODesk8.setColumns(20);
        ODesk8.setRows(5);
        ODeskPane8.setViewportView(ODesk8);

        ODeskLabel9.setText("Desk 9");

        ODeskPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane9.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk9.setEditable(false);
        ODesk9.setColumns(20);
        ODesk9.setRows(5);
        ODeskPane9.setViewportView(ODesk9);

        ODeskLabel10.setText("Desk 10");

        ODeskPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane10.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk10.setEditable(false);
        ODesk10.setColumns(20);
        ODesk10.setRows(5);
        ODeskPane10.setViewportView(ODesk10);

        ODeskLabel11.setText("Desk 11");

        ODeskPane11.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane11.setToolTipText("");
        ODeskPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane11.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk11.setEditable(false);
        ODesk11.setColumns(20);
        ODesk11.setRows(5);
        ODeskPane11.setViewportView(ODesk11);

        ODeskLabel12.setText("Desk 12");

        ODeskPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane12.setToolTipText("");
        ODeskPane12.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane12.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk12.setEditable(false);
        ODesk12.setColumns(20);
        ODesk12.setRows(5);
        ODeskPane12.setViewportView(ODesk12);

        ODeskLabel13.setText("Desk 13");

        ODeskPane13.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane13.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane13.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk13.setEditable(false);
        ODesk13.setColumns(20);
        ODesk13.setRows(5);
        ODeskPane13.setViewportView(ODesk13);

        ODeskLabel14.setText("Desk 14");

        ODeskPane14.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane14.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane14.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk14.setEditable(false);
        ODesk14.setColumns(20);
        ODesk14.setRows(5);
        ODeskPane14.setViewportView(ODesk14);

        ODeskLabel15.setText("Desk 15");

        ODeskPane15.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane15.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane15.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk15.setEditable(false);
        ODesk15.setColumns(20);
        ODesk15.setRows(5);
        ODeskPane15.setViewportView(ODesk15);

        ODeskLabel16.setText("Desk 16");

        ODeskPane16.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane16.setToolTipText("");
        ODeskPane16.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane16.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk16.setEditable(false);
        ODesk16.setColumns(20);
        ODesk16.setRows(5);
        ODeskPane16.setViewportView(ODesk16);

        ODeskLabel17.setText("Desk 17");

        ODeskPane17.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane17.setToolTipText("");
        ODeskPane17.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane17.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk17.setEditable(false);
        ODesk17.setColumns(20);
        ODesk17.setRows(5);
        ODeskPane17.setViewportView(ODesk17);

        ODeskLabel18.setText("Desk 18");

        ODeskPane18.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane18.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane18.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk18.setEditable(false);
        ODesk18.setColumns(20);
        ODesk18.setRows(5);
        ODeskPane18.setViewportView(ODesk18);

        ODeskLabel19.setText("Desk 19");

        ODeskPane19.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane19.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane19.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk19.setEditable(false);
        ODesk19.setColumns(20);
        ODesk19.setRows(5);
        ODeskPane19.setViewportView(ODesk19);

        ODeskLabel20.setText("Desk 20");

        ODeskPane20.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ODeskPane20.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ODeskPane20.setPreferredSize(new java.awt.Dimension(100, 50));

        ODesk20.setEditable(false);
        ODesk20.setColumns(20);
        ODesk20.setRows(5);
        ODeskPane20.setViewportView(ODesk20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ObservationRoomLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ReceptionLabel)
                        .addGap(668, 668, 668)
                        .addComponent(RestroomLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ODeskPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ODeskPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ODeskPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ODeskPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ODeskPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ODeskPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ODeskLabel14))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ODeskLabel15)
                                            .addComponent(ODeskPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ODeskPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskLabel6)
                                    .addComponent(ODeskLabel16)))
                            .addComponent(ODeskLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ODeskPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ODeskPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ODeskLabel7)
                            .addComponent(ODeskLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ODeskPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ODeskPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ODeskLabel8)
                            .addComponent(ODeskLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ODeskPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ODeskLabel10)
                                    .addComponent(ODeskPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ODeskPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ODeskLabel20)
                                    .addComponent(ODeskPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VaccinationRoomLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VDeskPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VDeskPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VDeskLabel1)
                                    .addComponent(VDeskLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VDeskPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VDeskPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VDeskLabel2)
                                    .addComponent(VDeskLabel7)
                                    .addComponent(ODeskLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VDeskPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VDeskPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VDeskLabel3)
                                    .addComponent(VDeskLabel8)
                                    .addComponent(ODeskLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(VDeskPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VDeskLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(VDeskLabel5)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(VDeskPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(VVaccinesLabel)
                                                    .addComponent(VVaccinesPane, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(VDeskPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VDeskLabel9)
                                            .addComponent(ODeskLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ODeskLabel5)
                                            .addComponent(VDeskLabel10)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(VDeskPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(VAuxiliaryLabel)
                                                    .addComponent(VAuxiliaryPane, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ReceptionTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RPatientLabel)
                                    .addComponent(RPatientTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RAuxiliaryTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RAuxiliaryLabel))))
                        .addGap(73, 73, 73)
                        .addComponent(RestroomTextPane)))
                .addGap(0, 143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReceptionLabel)
                    .addComponent(RestroomLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(RestroomTextPane, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(ReceptionTextPane))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RPatientLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RPatientTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RAuxiliaryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RAuxiliaryTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(VaccinationRoomLabel)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VDeskLabel1)
                            .addComponent(VDeskLabel2)
                            .addComponent(VDeskLabel3)
                            .addComponent(VDeskLabel4)
                            .addComponent(VDeskLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VDeskPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VDeskPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VDeskPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VDeskPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VDeskPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VVaccinesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VVaccinesPane, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VDeskLabel6)
                                    .addComponent(VDeskLabel8)
                                    .addComponent(VDeskLabel9)
                                    .addComponent(VDeskLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(VDeskPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VDeskPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(VAuxiliaryLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(VAuxiliaryPane, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(VDeskPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(VDeskPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(VDeskPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addComponent(ObservationRoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ODeskLabel1)
                                    .addComponent(ODeskLabel2)
                                    .addComponent(ODeskLabel3)
                                    .addComponent(ODeskLabel4)
                                    .addComponent(ODeskLabel5)
                                    .addComponent(ODeskLabel6)
                                    .addComponent(ODeskLabel7)
                                    .addComponent(ODeskLabel8)
                                    .addComponent(ODeskLabel9)
                                    .addComponent(ODeskLabel10)))
                            .addComponent(VDeskLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ODeskPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ODeskLabel11)
                                    .addComponent(ODeskLabel12)
                                    .addComponent(ODeskLabel13)
                                    .addComponent(ODeskLabel14)
                                    .addComponent(ODeskLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ODeskPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ODeskPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ODeskLabel16)
                                    .addComponent(ODeskLabel17)
                                    .addComponent(ODeskLabel18)
                                    .addComponent(ODeskLabel19)
                                    .addComponent(ODeskLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ODeskPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ODeskPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(960, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
   
    public javax.swing.JTextArea getReception(){
        return ReceptionText;
    }
    public javax.swing.JTextArea getReceptionPatient(){
        return RPatientText;
    }
    public javax.swing.JTextArea getReceptionAux(){
        return RAuxiliaryText;
    }
    public javax.swing.JTextArea getRestRoom(){
        return RestroomText;
    }
    public ArrayList<javax.swing.JTextArea> getVDesks(){
        ArrayList<javax.swing.JTextArea> l = new ArrayList<>();
        l.add(VDesk1);
        l.add(VDesk2);
        l.add(VDesk3);
        l.add(VDesk4);
        l.add(VDesk5);
        l.add(VDesk6);
        l.add(VDesk7);
        l.add(VDesk8);
        l.add(VDesk9);
        l.add(VDesk10);
        return l;
    }
    public javax.swing.JTextArea getVaccines(){
        return VVaccinesText;
    }
    public javax.swing.JTextArea getVaccRoomAux(){
        return VAuxiliaryText;
    }
    public ArrayList<javax.swing.JTextArea> getODesks(){
        ArrayList<javax.swing.JTextArea> l = new ArrayList<>();
        l.add(ODesk1);
        l.add(ODesk2);
        l.add(ODesk3);
        l.add(ODesk4);
        l.add(ODesk5);
        l.add(ODesk6);
        l.add(ODesk7);
        l.add(ODesk8);
        l.add(ODesk9);
        l.add(ODesk10);
        l.add(ODesk11);
        l.add(ODesk12);
        l.add(ODesk13);
        l.add(ODesk14);
        l.add(ODesk15);
        l.add(ODesk16);
        l.add(ODesk17);
        l.add(ODesk18);
        l.add(ODesk19);
        l.add(ODesk20);
        return l;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ODesk1;
    private javax.swing.JTextArea ODesk10;
    private javax.swing.JTextArea ODesk11;
    private javax.swing.JTextArea ODesk12;
    private javax.swing.JTextArea ODesk13;
    private javax.swing.JTextArea ODesk14;
    private javax.swing.JTextArea ODesk15;
    private javax.swing.JTextArea ODesk16;
    private javax.swing.JTextArea ODesk17;
    private javax.swing.JTextArea ODesk18;
    private javax.swing.JTextArea ODesk19;
    private javax.swing.JTextArea ODesk2;
    private javax.swing.JTextArea ODesk20;
    private javax.swing.JTextArea ODesk3;
    private javax.swing.JTextArea ODesk4;
    private javax.swing.JTextArea ODesk5;
    private javax.swing.JTextArea ODesk6;
    private javax.swing.JTextArea ODesk7;
    private javax.swing.JTextArea ODesk8;
    private javax.swing.JTextArea ODesk9;
    private javax.swing.JLabel ODeskLabel1;
    private javax.swing.JLabel ODeskLabel10;
    private javax.swing.JLabel ODeskLabel11;
    private javax.swing.JLabel ODeskLabel12;
    private javax.swing.JLabel ODeskLabel13;
    private javax.swing.JLabel ODeskLabel14;
    private javax.swing.JLabel ODeskLabel15;
    private javax.swing.JLabel ODeskLabel16;
    private javax.swing.JLabel ODeskLabel17;
    private javax.swing.JLabel ODeskLabel18;
    private javax.swing.JLabel ODeskLabel19;
    private javax.swing.JLabel ODeskLabel2;
    private javax.swing.JLabel ODeskLabel20;
    private javax.swing.JLabel ODeskLabel3;
    private javax.swing.JLabel ODeskLabel4;
    private javax.swing.JLabel ODeskLabel5;
    private javax.swing.JLabel ODeskLabel6;
    private javax.swing.JLabel ODeskLabel7;
    private javax.swing.JLabel ODeskLabel8;
    private javax.swing.JLabel ODeskLabel9;
    private javax.swing.JScrollPane ODeskPane1;
    private javax.swing.JScrollPane ODeskPane10;
    private javax.swing.JScrollPane ODeskPane11;
    private javax.swing.JScrollPane ODeskPane12;
    private javax.swing.JScrollPane ODeskPane13;
    private javax.swing.JScrollPane ODeskPane14;
    private javax.swing.JScrollPane ODeskPane15;
    private javax.swing.JScrollPane ODeskPane16;
    private javax.swing.JScrollPane ODeskPane17;
    private javax.swing.JScrollPane ODeskPane18;
    private javax.swing.JScrollPane ODeskPane19;
    private javax.swing.JScrollPane ODeskPane2;
    private javax.swing.JScrollPane ODeskPane20;
    private javax.swing.JScrollPane ODeskPane3;
    private javax.swing.JScrollPane ODeskPane4;
    private javax.swing.JScrollPane ODeskPane5;
    private javax.swing.JScrollPane ODeskPane6;
    private javax.swing.JScrollPane ODeskPane7;
    private javax.swing.JScrollPane ODeskPane8;
    private javax.swing.JScrollPane ODeskPane9;
    private javax.swing.JLabel ObservationRoomLabel;
    private javax.swing.JLabel RAuxiliaryLabel;
    private javax.swing.JTextArea RAuxiliaryText;
    private javax.swing.JScrollPane RAuxiliaryTextPane;
    private javax.swing.JLabel RPatientLabel;
    private javax.swing.JTextArea RPatientText;
    private javax.swing.JScrollPane RPatientTextPane;
    private javax.swing.JLabel ReceptionLabel;
    private javax.swing.JTextArea ReceptionText;
    private javax.swing.JScrollPane ReceptionTextPane;
    private javax.swing.JLabel RestroomLabel;
    private javax.swing.JTextArea RestroomText;
    private javax.swing.JScrollPane RestroomTextPane;
    private javax.swing.JLabel VAuxiliaryLabel;
    private javax.swing.JScrollPane VAuxiliaryPane;
    private javax.swing.JTextArea VAuxiliaryText;
    private javax.swing.JTextArea VDesk1;
    private javax.swing.JTextArea VDesk10;
    private javax.swing.JTextArea VDesk2;
    private javax.swing.JTextArea VDesk3;
    private javax.swing.JTextArea VDesk4;
    private javax.swing.JTextArea VDesk5;
    private javax.swing.JTextArea VDesk6;
    private javax.swing.JTextArea VDesk7;
    private javax.swing.JTextArea VDesk8;
    private javax.swing.JTextArea VDesk9;
    private javax.swing.JLabel VDeskLabel1;
    private javax.swing.JLabel VDeskLabel10;
    private javax.swing.JLabel VDeskLabel2;
    private javax.swing.JLabel VDeskLabel3;
    private javax.swing.JLabel VDeskLabel4;
    private javax.swing.JLabel VDeskLabel5;
    private javax.swing.JLabel VDeskLabel6;
    private javax.swing.JLabel VDeskLabel7;
    private javax.swing.JLabel VDeskLabel8;
    private javax.swing.JLabel VDeskLabel9;
    private javax.swing.JScrollPane VDeskPane1;
    private javax.swing.JScrollPane VDeskPane10;
    private javax.swing.JScrollPane VDeskPane2;
    private javax.swing.JScrollPane VDeskPane3;
    private javax.swing.JScrollPane VDeskPane4;
    private javax.swing.JScrollPane VDeskPane5;
    private javax.swing.JScrollPane VDeskPane6;
    private javax.swing.JScrollPane VDeskPane7;
    private javax.swing.JScrollPane VDeskPane8;
    private javax.swing.JScrollPane VDeskPane9;
    private javax.swing.JLabel VVaccinesLabel;
    private javax.swing.JScrollPane VVaccinesPane;
    private javax.swing.JTextArea VVaccinesText;
    private javax.swing.JLabel VaccinationRoomLabel;
    // End of variables declaration//GEN-END:variables
}
